#!/bin/sh /etc/rc.common
# Copyright (C) 2005-2013 NowRush Studio
# Author: hackpascal <hackpascal@gmail.com>

START=70

stop() {
	for port in $(seq -s ' ' 0 9); do
		PID_F=/var/run/p910${port}d.pid
		[ -f $PID_F ] && kill $(cat $PID_F)
	done
}

start() {
	for lps in $(/usr/sbin/usb_printer_detect); do
		product=$(echo $lps | cut -d , -f 2)

		/usr/sbin/usb_printer_hotplug "$product" add
	done
}

restart() {
	stop
	start
}
